<a href="https://colab.research.google.com/github/ataulhaque/ML/blob/main/XGBoost_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#importing libraries
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import xgboost as xgb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder

In [3]:
#upload the churn_modeling.csv file
from google.colab import files
uploaded = files.upload()


Saving Churn_Modelling.csv to Churn_Modelling.csv


In [4]:
#Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.shape

(10000, 14)

In [6]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
#

In [15]:
#Check the shape and first row values of X - numpy array to help identify columns to be encoded for categorical values
print(X.shape)
X[0]

(10000, 10)


array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [16]:
#Encoding categorical data to convert column 1 and 2 into numerical values
LabelEncoder_X_1 = LabelEncoder()
X[:, 1] = LabelEncoder_X_1.fit_transform(X[:, 1])

LabelEncoder_X_2 = LabelEncoder()
X[:, 2] = LabelEncoder_X_2.fit_transform(X[:, 2])
#

In [20]:
#check for transformed values
print(X[0, 1])
print(X[0, 2])
#

0
0


In [21]:
#Splitting the dataset into training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
#

In [22]:
#Fitting XGBoost to the training data
model = xgb.XGBClassifier()
model.fit(X_train, y_train)
#
#Predicting the test set results
y_pred = model.predict(X_test)
#
#Making the confusion matrix
cm = confusion_matrix(y_test, y_pred)

In [23]:
cm

array([[1493,  102],
       [ 198,  207]])

In [24]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
model.score(X_test, y_test)

0.85

In [28]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:",)
print (result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
#print accuracy_score
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[1493  102]
 [ 198  207]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.94      0.91      1595
           1       0.67      0.51      0.58       405

    accuracy                           0.85      2000
   macro avg       0.78      0.72      0.74      2000
weighted avg       0.84      0.85      0.84      2000

Accuracy: 0.85
